---
# IPA server configuration
ipaserver_domain: example.com
ipaserver_realm: EXAMPLE.COM
ipaserver_ip: 192.168.1.163

# IPA credentials
ipaserver_admin_password: "{{ vault_ipaserver_admin_password }}"
ipaserver_dir_manager_password: "{{ vault_ipaserver_dir_manager_password }}"

# NFS configuration
nfs_export_dir: /home
nfs_server_ip: 192.168.1.163
