[ipaserver]
ipa01.example.test

[ipaclients]
client01.example.test
client02.example.test
client03.example.test

[nfsserver]
ipa01.example.test  # NFS is co-located with IPA for this lab environment

[lab:children]
ipaserver
ipaclients
